# Generated by Django 5.1.1 on 2025-01-11 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_box_availability_date_box_availability_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='student',
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='unknown@parisnanterre.fr', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default='10:00:00'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='box',
            name='availability_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='availability_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='box',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
